<!DOCTYPE html>
<html>
<head>
	<title>Tabel Layout</title>
</head>
<body>
	<table border="1" width="1350" bgcolor="blue"></table>
	<table border="3" width="150" bgcolor="blue">
		<tr>
			<td height="150px">
			<img src="Logo.png">
			</td>
		</tr>
	</table>
	<table border="1" width="1350" >
		<tr> 
			<td height="55" bgcolor="blue">
			<text><center>Home &nbsp Profil &nbsp Fakultas &nbsp Mahasiswa</center></text>
			</td>
		</tr>
	</table>
	&nbsp 
	<center><table border="1" width="100">&nbsp
			<table border="1" width="100">
		<tr>
				<td height="55px" bgcolor="blue">
					<img src="Manchester United.png">
				</td>
					<td border ="1" width="150" /> &nbsp &nbsp &nbsp
				<td height="55px" bgcolor="blue">
					<img src="Barcelona.png">
				</td>
		</tr>
		<tr>
			<td><b>Manchester United</b> adalah sebuah club sepak bola profesional inggris yang berbasis di Old Trafford,Manchester Raya,yang bermain di liga inggris. Didirikan sebagai Newton Heath LYR Football Club pada tahun 1878,klub ini berganti nama menjadi Manchester Uniter pada 1902 dan pindah ke Old Trafford pada tahun 1910</td>

			<td> &nbsp &nbsp &nbsp &nbsp &nbsp </td>

			<td><b>Futbol Club Barcelona</b> juga dikenal sebagai <b>Barcelona</b> adalah club sepak bola profesional yang berbasis di Barcelona,Catalunya,Spanyol. Didirikan pada tahun 1899 oleh sekelompok pemain Swiss,Inggris,Jerman, dan Katalan yang dipimpin oleh Joan Gamper,klub telah menjadi simbol budaya Catalan dan Catalanisme,yang mempunyai motto "Mes que un club"</td>
		</tr>
	</center></table>
			</table>
	&nbsp
	<footer>
	<table border="1" width="1350">
		<td height="55" bgcolor="blue">
		 <text><center><b> Mohammad Revy Zanuar Nur Wahid@copyright 2020 </b></center></text>
		</td>
	</table>
	</footer>
</body>
</html>